### ISSUE TITLE
FileLoadException with .NET Framework, .NET Standard, and Accord.Statistics

### ISSUE THREAD

**Issue by paulirwin** [accord-net/framework#1426]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [X] bug report
  - [ ] feature request

**Issue description**

I am able to reproduce with a simple example a `FileLoadException` trying to load Accord.Statistics 3.8.0 when the entry assembly is a .NET Framework 4.6.1 or later app and the reference to Accord.Statistics is via a .NET Standard 1.4 or 2.0 library. This first manifest itself when I tried changing one of our class libraries that uses Accord.Statistics from net471 to netstandard2.0.

Error details:
```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Accord.Statistics, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=ClassLibrary1
  StackTrace:
   at ClassLibrary1.Class1.DoMath() in [... path ...]\repos\ConsoleApp2\ClassLibrary1\Class1.cs:line 11
   at ConsoleApp2.Program.Main(String[] args) in [... path ...]\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 14
```

Reproduction steps:
1. Create a new .NET Framework 4.7.1 console app. I am using the new VS2017 project format. (csproj below) In my examples it is called ConsoleApp2
2. Add to the solution a new .NET Standard 2.0 library. (csproj below) In my examples it is called ClassLibrary1
3. Add a reference in ConsoleApp2 to ClassLibrary1
4. Add a NuGet reference in ClassLibrary1 to Accord.Statistics 3.8.0
5. Add a call to an Accord.Statistics function in the class library code.
6. Add a call to the class library code from the main entry point.
7. Run app, crash

ConsoleApp2.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <OutputType>EXE</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

ClassLibrary1.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Accord.Statistics" Version="3.8.0" />
  </ItemGroup>

</Project>
```

ClassLibrary1\Class1.cs:
```c#
using Accord.Statistics.Models.Regression.Linear;

namespace ClassLibrary1
{
    public class Class1
    {
        public double DoMath()
        {
            return SimpleLinearRegression.FromData(new[] { 0.75, 0.8 }, new[] { 0.75, 0.8 }).Slope;
        }
    }
}
```

ConsoleApp2\Program.cs:
```c#
using System;
using ClassLibrary1;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var result = new Class1().DoMath();
            Console.WriteLine(result);
        }
    }
}
```

I also tried referencing Accord.Statistics 3.8.0 directly from the console app entry point, but that did not help at all, got the same error. My hunch is that something is wrong with the references for the netstandard2.0 DLLs, because if you change ClassLibrary1 to target net471 it works fine. I have tested that this occurs when the console app is set to .NET Framework 4.6.1, 4.6.2, 4.7, or 4.7.1, and if the class library is set to .NET Standard 1.4 or 2.0 (the two .NET Standard versions supported by Accord.Statistics).

**Comment by pcameron-** [comment]
I am having the same exact issue with Accord.Math 3.8.0. There is something odd going on with the dll signing. The net standard 2.0 dll's public keys are null but the .NET Framework 4.7.1 have a public key. When we do a build of our .NET Framework 4.7.1 project that references a project in net standard 2.0, the bin folder contains a version of Accord.Math with a public key. The run-time exception is saying it can't find Accord.Math since is looking for one with a null public key. If I replace the dlls in the bin folder after I build with the net standard 2.0 ones, I do not get the run-time exception.

**Comment by AndreasWilladsen** [comment]
Workaround until ALL Accord dll's are signed:

Make your netstandard project that you're consuming from the full .net framework target multiple frameworks by modifying the csproj file. In my case with .Net 4.6.1:

Before: `<TargetFramework>netstandard2.0</TargetFramework>`
After: `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`

That makes your application pick up the correct (signed) dll because it will consume the .net framework part of your library

**Comment by mattfrear** [comment]
I found this googling because I was having a similar problem with `ServiceStack.Text`'s NuGet package, and Andreas' workaround worked for me. Thanks!

**Comment by AndreasWilladsen** [comment]
@mattfrear it's because not all of the dll's in Accord are signed. It's been a while so I can't remember if it's the full framework or the netstandard version that isn't signed, which creates this mess. If just Accord would sign all dll's when building this wouldn't be an issue

**Comment by trishorts** [comment]
How about it, Accord? Would you provide signed dlls? I have app that is limited to netstandard2/netcoreapp2 and won't build when adding net461. can't use that workaround.

**Comment by Grepsy** [comment]
We're also running into this; gonna look at replacing Accord with another lib.

**Comment by johnmetta** [comment]
Bump. Me too, @Grepsy. Can't work around it, thinking of using Math.Net instead. Shame that I can't use the tool because of a seemingly simple build problem.
