### ISSUE TITLE
Cobyla Nonlinear Constraints

### ISSUE THREAD

**Issue by pereiraTTW** [accord-net/framework#1557]
- [x] question
  - [x] bug report
  - [ ] feature request

Hello!

I'm getting some random behaviour using Bounds in Cobyla. 
`cobyla = new Cobyla(CobylaFunction, constraints.ToArray());`

I have 4 variables. If I build the `constraints` array as follows:
```
List<NonlinearConstraint> constraints = new List<NonlinearConstraint>();
for (int vv = 0; vv < varCount; vv++)
    constraints.Add(new NonlinearConstraint(varCount, x => x[vv], ConstraintType.GreaterThanOrEqualTo, LowerBounds[vv]));
```

I get the following exception error:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Script_Instance.<>c__DisplayClassc.<RunScript>b__4(Double[] x) in c:\Users\andrep\AppData\Local\Temp\zf0b3kuc.0.cs:line 323
   at Accord.Math.Optimization.ConstraintExtensions.GetViolation(IConstraint constraint, Double[] input)
   at Accord.Math.Optimization.Cobyla.cobyla()
   at Accord.Math.Optimization.Cobyla.Optimize()
   at Accord.Math.Optimization.BaseOptimizationMethod.Minimize()
```

If I add only 3 constraints (for the first 3 variables)
```
for (int vv = 0; vv < varCount - 1; vv++)
     constraints.Add(new NonlinearConstraint(varCount, x => x[vv], ConstraintType.GreaterThanOrEqualTo, LowerBounds[vv]));
```
it runs the solver, but completely ignores the value of `LowerBounds[vv]`.

Now, and this is when things get weird, if I build constraint list outside of a for loop
```
List<NonlinearConstraint> constraints2 = new List<NonlinearConstraint>();

int zz = 0;
constraints2.Add(new NonlinearConstraint(varCount, x => x[zz], ConstraintType.GreaterThanOrEqualTo, LowerBounds[zz]));

zz++;
constraints2.Add(new NonlinearConstraint(varCount, x => x[zz], ConstraintType.GreaterThanOrEqualTo, LowerBounds[zz]));

zz++;
constraints2.Add(new NonlinearConstraint(varCount, x => x[zz], ConstraintType.GreaterThanOrEqualTo, LowerBounds[zz]));
```

It runs fine and constraints are fulfilled.

Any idea of what can cause this behavior?

Many thanks!

**Comment by pereiraTTW** [comment]
Anyone?

**Comment by ndkazu** [comment]
Hello,
I have exactly the same problem, did you find a solution?]
Kazu

**Comment by pereiraTTW** [comment]
Hi ndkazu,

Yes, your for loops must have the form:
`foreach (var indexVar in Enumerable.Range(0, countVar))`
