### ISSUE TITLE
ScatterplotBox SetLinesVisible throws System.InvalidOperationException

### ISSUE THREAD

**Issue by MuSamiNaf** [accord-net/framework#1582]
I am having an issue with the SetLinesVisible Method.

The following code throws an exception 

> System.InvalidOperationException occurred
>   HResult=0x80131509
>   Message=Cross-thread operation not valid: Control 'zedGraphControl' accessed from a thread other than the thread it was created on.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
>    at System.Windows.Forms.Control.get_Handle()
>    at System.Windows.Forms.Control.Invalidate(Boolean invalidateChildren)
>    at System.Windows.Forms.Control.Refresh()
>    at ZedGraph.ZedGraphControl.RestoreScale(GraphPane primaryPane)
>    at Accord.Controls.ScatterplotView.UpdateGraph()
>    at Accord.Controls.ScatterplotBox.SetLinesVisible(Boolean visible)
>    at ConsoleApp28.Program.Main(String[] args) in c:\users\atomic.adminrg-7uq6vs4\documents\visual studio 2017\Projects\ConsoleApp28\ConsoleApp28\Program.cs:line 111
> 

```
Scatterplot sp = new Scatterplot("Roc Curve", "FPR", "Senstivty");
sp.Compute(xAxis, yAxis);

ScatterplotBox.Show(sp).SetLinesVisible(true);

```
If I didn't use the method, the scatterploxbox plots all the points disconnected from each other. 
I have tried the code found [here](http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_ReceiverOperatingCharacteristic.htm), 
but same issue.

Am I missing something?

Thanks

**Comment by vmostransistor** [comment]
I have the same problem:
`            ScatterplotBox.Show("Deltas", deltas.ToArray())
                .SetSymbolSize(0)
                .SetLinesVisible(true)
                .WaitForClose();`

System.InvalidOperationException
  HResult=0x80131509
  Message=Cross-thread operation not valid: Control 'zedGraphControl' accessed from a thread other than the thread it was created on.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.Invalidate(Boolean invalidateChildren)
   at System.Windows.Forms.Control.Refresh()
   at ZedGraph.ZedGraphControl.RestoreScale(GraphPane primaryPane)
   at Accord.Controls.ScatterplotView.UpdateGraph()
   at Accord.Controls.ScatterplotBox.SetSymbolSize(Single size)
   at Deep_Learning.MainWindow.Button_Use_Accord_NN(Object sender, RoutedEventArgs e) in C:\Projects\Visual Studio\Deep Learning\Deep Learning\MainWindow.xaml.cs:line 393
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Deep_Learning.App.Main()
