### ISSUE TITLE
IndexOutOfRangeException on BagOfVisualWords.Learn

### ISSUE THREAD

**Issue by miker1423** [accord-net/framework#1621]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
I'm trying to use the BagOfVisualWords to extract the features from some images to train an SVM (as shown a sample), but every time I try to run the Learn method on the BagOfVisualWords it throws and IndexOutOfBoundsException. I isolated that piece of code, it looks like this:
```csharp
            var directory = "mydirectory";
            var bitmaps = new List<Bitmap>();
            foreach (var file in Directory.GetFiles(directory))
                bitmaps.Add(new Bitmap(file));

            var binarySplit = new BinarySplit(10);
            var surfBow = new BagOfVisualWords(binarySplit);
            surfBow.Learn(bitmaps.ToArray());
```
the full stack trace is the next one:

at Accord.Math.Matrix.Max[T](T[] values, Int32& imax)
at Accord.Math.Vector.Histogram(Int32[] labels)
at Accord.MachineLearning.BaseBagOfWords`6.InnerLearn[T](T[] x, Double[] weights, Func`3 extractor)
at Accord.Imaging.BaseBagOfVisualWords`5.Learn(Bitmap[] x, Double[] weights)
at ClassificationSVM.MainWindow.CreateBow() at C:\Users\migue\Source\Repos\SVMClassifier\src\ClassificationSVM\MainWindow.xaml.cs:línea 175
en ClassificationSVM.MainWindow.<Learn_Clicked>b__3_0() en C:\Users\migue\Source\Repos\SVMClassifier\src\ClassificationSVM\MainWindow.xaml.cs:línea 79

Note: my images are small, about 12x12 pixels, I don't know if it is related.

**Comment by miker1423** [comment]
After cloning the repository, compiling the library, replacing all references, I found that it is caused because it cannot take any descriptor from the image, so, I guess I'm lost here...
