### ISSUE TITLE
Codification.Save() throws exception on .net core 3.0

### ISSUE THREAD

**Issue by iansmirlis** [accord-net/framework#2011]
- [x] bug report

**Issue description**

Below code
```
DataTable data = PrepareData(); 
var codebook = new Codification(data);
codebook.Save("code.dat");
```

Throws following exception at runtime:
```
Unhandled exception. System.Runtime.Serialization.SerializationException: Serializing delegates is not supported on this platform.
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Accord.IO.Serializer.Save[T](T obj, BinaryFormatter formatter, Stream stream, SerializerCompression compression)
   at Accord.IO.Serializer.Save[T](T obj, Stream stream, SerializerCompression compression)
   at Accord.IO.Serializer.Save[T](T obj, String path, SerializerCompression compression)
   at Accord.IO.Serializer.Save[T](T obj, String path)
   at hyphen.Program.Train() in /home/ian/src/trunk/utils/hyphen/Program.cs:line 126
   at hyphen.Program.Main(String[] args) in /home/ian/src/trunk/utils/hyphen/Program.cs:line 83
```

I'm using Accord.Net 3.8.0 and .NET Core SDK 3.0.101 on Linux Debian 10

**Comment by blaisexen** [comment]
Hi,

On Windows what is the result?

**Comment by iansmirlis** [comment]
Hi,

It has the same behavior on windows

Below code:
```
            DataTable table = new DataTable("Sample data");
            table.Columns.Add("Age", typeof(int));
            table.Columns.Add("Label", typeof(string));

            table.Rows.Add(10, "child");
            table.Rows.Add(07, "child");
            table.Rows.Add(04, "child");
            table.Rows.Add(21, "adult");
            table.Rows.Add(27, "adult");
            table.Rows.Add(12, "child");
            table.Rows.Add(79, "elder");
            table.Rows.Add(40, "adult");
            table.Rows.Add(30, "adult");


            var codebook = new Codification(table);
            codebook.Save("test.dat");
```

Throws:
```
Unhandled exception. System.Runtime.Serialization.SerializationException: Serializing delegates is not supported on this platform.
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter, Boolean fCheck)  
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Boolean check)     
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Accord.IO.Serializer.Save[T](T obj, BinaryFormatter formatter, Stream stream, SerializerCompression compression)
   at Accord.IO.Serializer.Save[T](T obj, Stream stream, SerializerCompression compression)
   at Accord.IO.Serializer.Save[T](T obj, String path, SerializerCompression compression)
   at Accord.IO.Serializer.Save[T](T obj, String path)
   at tmp.Program.Main(String[] args) in C:\Users\ian\tmp\Program.cs:line 36
```
.Net core 3.0.100 on WIndows 10

It seems that .net core does not support serialization of delegates:
[https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization](url)

Does a Codification object need to serialize delegates?

**Comment by blaisexen** [comment]
Hi,
could you try like this, i don't have now a vs test but at-least you can try it
DataTable table; //declare public if ok
Codification codebook; //declare public if ok
 
.
.
table = new DataTable("Sample data");
codebook = new Codification(table);
.
.
.
.
codebook.Save("test.dat");

**Comment by iansmirlis** [comment]
Nope, declaring table and codebook as public, does not solve the issue.

**Comment by iansmirlis** [comment]
A quick and (very) dirty solution is to remove the AddingNew delegates from ColumnOptionCollection that it tries to serialize:


```
var c = new Codification( data );

var classType = c.Columns.GetType();
var eventField = classType.GetField("AddingNew", BindingFlags.GetField | BindingFlags.NonPublic | BindingFlags.Instance); 
var e = (System.EventHandler<Codification<string>.Options>)eventField.GetValue(c.Columns);
foreach(var d in e.GetInvocationList()) c.Columns.AddingNew -= (System.EventHandler<Codification<string>.Options>) d;

c.Save("code.dat");
```

Maybe [field: NonSerialized] should be added on ColumnOptionCollection.cs AddingNew event?

```
[field: NonSerialized]
public event EventHandler<TOptions> AddingNew;
```
