### ISSUE TITLE
Exception on deserializing Codification Object

### ISSUE THREAD

**Issue by pkkarri** [accord-net/framework#263]
I serialized an object of Codification class and it went fine. I get the following null reference exception when I try to deserialize the stream into an object of codification. Let me know if I'm missing something here.

Exception:    at Accord.Collections.TwoWayDictionary`2.OnDeserialized(StreamingContext context) in *****\Accord.Core\Collections\TwoWayDictionary.cs:line 457
   at System.Runtime.Serialization.SerializationEventHandler.Invoke(StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at ***.WebApplication.Application_Start() in *****\Global.asax.cs:line 41

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
