### ISSUE TITLE
System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by heldersepu** [accord-net/framework#345]
I'm trying to use VideoFileWriter in a WebApi project and i get the error below.
Here is a sample project to duplicate the bug:
[Accord_Video_FFMPEG.zip](https://github.com/accord-net/framework/files/587023/Accord_Video_FFMPEG.zip)

```
System.Runtime.InteropServices.SEHException was unhandled by user code
  ErrorCode=-2147467259
  HResult=-2147467259
  Message=External component has thrown an exception.
  Source=Accord.Video.FFMPEG
  StackTrace:
       at av_register_all()
       at Accord.Video.FFMPEG.VideoFileWriter..ctor()
       at Accord_Video_FFMPEG.Controllers.DefaultController.Get() in L:\csharp-proj\Accord_Video_FFMPEG\Accord_Video_FFMPEG\Controllers\DefaultController.cs:line 10
       at lambda_method(Closure , Object , Object[] )
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
  InnerException: 

```

**Comment by heldersepu** [comment]
This is only happening with WebApi on a Console project it woks fine...

**Comment by ChenZhaobin** [comment]
I met with the same problem,Anyone helpes?

**Comment by heldersepu** [comment]
I managed to get around by not using ccord.Video.FFMPEG
instead using this:
http://www.codeproject.com/Articles/7388/A-Simple-C-Wrapper-for-the-AviFile-Library

**Comment by MelvinGr** [comment]
I have made a pull request fixing this: [accord-net/framework/pull/349](https://github.com/accord-net/framework/pull/349)

**Comment by ChenZhaobin** [comment]
I meant to get the result in format of mp4 instead of avi,how can I do that?

**Comment by rdt23** [comment]
does anyone has solotion to the problame using  Accord.Video.FFMPEG?

**Comment by cesarsouza** [comment]
Just as an update, this should have been fixed some releases ago.
