### ISSUE TITLE
Error while encoding video frame

### ISSUE THREAD

**Issue by epreto** [accord-net/framework#714]
Hello,

I'm trying to record a video from usb device in c# (WTF)

I make this method (always called when a new frame arrives):

`private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            try
            {
                if (_recording)
                {
                    if (_firstFrameTime != null)
                    {
                        _writer.WriteVideoFrame(eventArgs.Frame, DateTime.Now - _firstFrameTime.Value);
                    }
                    else
                    {
                        _writer.WriteVideoFrame(eventArgs.Frame);
                        _firstFrameTime = DateTime.Now;
                    }
                }
                using (var bitmap = (Bitmap)eventArgs.Frame.Clone())
                {
                    Image = bitmap.ToBitmapImage();
                }
                Image.Freeze(); // avoid cross thread operations and prevents leaks
            }
            catch (Exception exc)
            {
                MessageBox.Show("Error on _videoSource_NewFrame:\n" + exc.Message, "Error", MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }`

However a always have this run time error: 
"Accord.Video.VideoException: 'Error while encoding video frame'"
Any Help?

**Comment by Otaku81** [comment]
I had the same problem. In my application I figured out that it does not stop to record when the exception triggers. It just freezes until I click the OK button of the message box and then takes the next frame, triggers the exception again and so on....

so I just kept the catch-block empty and now I can record videos from my USB-device. not an optimal solution but a working one.

**Comment by hsafavi** [comment]
i have same problem. it happens when i use  _writer.WriteVideoFrame(Bitmap,Timespan) overload. the aforg has no problem with this overload but accord!

**Comment by cesarsouza** [comment]
This issue will be fixed in the next release with the [rewrite of the VideoFileWriter class](https://github.com/accord-net/framework/issues/1001).

**Comment by cesarsouza** [comment]
A new (pre-release) version of Accord.Video.FFMPEG has just been pushed to NuGet. If it helps solving the issue (and if it isn't too late for you of course, as I realize it has been some time since the issue was first opened), please let me know!

Regards,
Cesar

**Comment by ukrgerri4** [comment]
Hi, thanks for your work. I installed new 'Accord.3.8.2-alpha' and still have error while try save video.
I use the same code as the guy who discovered this problem. Empty 'catch' still allows to record video.

This is error: "Error encoding video frame. Error -1: Operation not permitted. See console output for more details."

StackTrace:
at Accord.Video.FFMPEG.CHECK(Int32 errorCode, String message)
at Accord.Video.FFMPEG.WriterPrivateData.write_video_frame(AVFormatContext* oc, OutputStream* ost, AVFrame* frame)
at Accord.Video.FFMPEG.WriterPrivateData.mux(WriterPrivateData* , AVFormatContext* oc, AVFrame* frame)
at Accord.Video.FFMPEG.WriterPrivateData.send_video_frame(WriterPrivateData* , OutputStream* ost, UInt64* bitmapData, Int32 stride)
at Accord.Video.FFMPEG.VideoFileWriter.WriteVideoFrame(BitmapData frame, TimeSpan timestamp)
at Accord.Video.FFMPEG.VideoFileWriter.WriteVideoFrame(Bitmap frame, TimeSpan timestamp)
at CaptureVideo.Main.video_NewFrame(Object sender, NewFrameEventArgs eventArgs) in E:\Projects\CaptureVideo\Main.cs:line 87

**Comment by cesarsouza** [comment]
Hi @ukrgerri4,

Change your application to become a console application. This will make a console window appear together with your application window when you run it. FFmpeg will write to the this console and you will be able to see what's exactly causing this issue there.

Hope it helps,
Cesar

**Comment by bradmh** [comment]
Also came across this issue, however having had a similar issue working on scripts for FFMPEG, I believe the root cause is the number of decimal places used by the .net definition of timespan and the ffmpeg timestamp definition.

FFMPEG accepts down to milliseconds for a frame timestamp (3 decimal places), whereas the .net implementation of timespan goes down to ticks (7 decimal places).

If you have used devices with fixed frame rates, you likely have had a timespan with a terminating decimal value, that hasnt fallen foul (ie 10 FPS / 25 FPS would give timespans of 0.1s / 0.04s between each frame).

If using devices with higher / non standard or variable frame rates (ie 30 FPS would give a timepsan of 0.016666666...s between each frame) then this timespan value causes the error within FFMPEG when trying to encode a frame.
A solution to this is to ensure you are using milliseconds when working with timespans / stopwatches as opposed to ticks, or to cover all bases, you could incorporate a RoundedTimeSpan structure / function, ensuring any timespan value is fully compatible with FFMPEG.

This could be built into the VideoFileWriter itself, to prevent the error being reraised in subsequent releases.

See example structure, modified from [http://cleancode.sourceforge.net/api/csharp/](url)
        
`using System;    
    public struct RoundedTimeSpan
    {

        private const int TIMESPAN_SIZE = 7; // it always has seven digits

        private TimeSpan roundedTimeSpan;
        private int precision;

        public RoundedTimeSpan(long ticks, int precision)
        {
            if (precision < 0) { throw new ArgumentException("precision must be non-negative"); }
            this.precision = precision;
            int factor = (int)System.Math.Pow(10, (TIMESPAN_SIZE - precision));

            // This is only valid for rounding milliseconds-will *not* work on secs/mins/hrs!
            roundedTimeSpan = new TimeSpan(((long)System.Math.Round((1.0 * ticks / factor)) * factor));
        }

        public TimeSpan TimeSpan { get { return roundedTimeSpan; } }
        }`

Which can then be used as

`_writer.WriteVideoFrame(eventArgs.Frame,(new RoundedTimeSpan((DateTime.Now - _firstFrameTime), 3));`

**Comment by argonautos** [comment]
This solution does not work for me. I've also tested it with the following similar method (which does not work as well):

```
private TimeSpan RoundTimeSpan(TimeSpan timeSpan)
{
    return new TimeSpan(timeSpan.Days, timeSpan.Hours, timeSpan.Minutes, timeSpan.Seconds, timeSpan.Milliseconds);
}
```

**Comment by MATRIX812010** [comment]
Hi all. 
this worked for exception "Error while writing frame", according to https://stackoverflow.com/questions/5955883/datetimes-representation-in-milliseconds
=======================================
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            try
            {
                if (_recording)
                {
                    using (var bitmap = CloneBitmap((Bitmap)eventArgs.Frame.Clone()))
                    {
                        if (_firstFrameTime != null)
                        {

                            _writer.WriteVideoFrame(bitmap, TimeSpan.FromMilliseconds(DateTime.Now.ToUniversalTime().Subtract(
    new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)
    ).TotalMilliseconds - _firstFrameTime.Value.ToUniversalTime().Subtract(
    new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)
    ).TotalMilliseconds));
                        }
                        else
                        {
                            _writer.WriteVideoFrame(bitmap);
                            _firstFrameTime = DateTime.Now;
                        }
                    }
                }
                using (var bitmap = (Bitmap)eventArgs.Frame.Clone())
                {
                    var bi = CloneBitmap(bitmap);
                    CurrentImage = bi;
                    pictureBox1.Image = bi;
                }
            }
            catch (Exception exc)
            {
                
            }
        }
        public Bitmap CloneBitmap(Bitmap bitmap)
        {
            Image bi;
            MemoryStream ms = new MemoryStream();
            bitmap.Save(ms, ImageFormat.Bmp);
            ms.Seek(0, SeekOrigin.Begin);
            bi = Image.FromStream(ms);
            ms.Close();
            return (Bitmap)bi;
        }

**Comment by Zilch123** [comment]
> Is there a solution available for this problem? MATRIX812010's solution is not resolving the exception for me.

Hi Mfranchitti, 
         Did you solve it? 
         I am trying to find the solution too. MATRIX812010's solution didn't work for me.

Thank you, 
Zuko

**Comment by postry** [comment]
Any update on this issue?
