### ISSUE TITLE
Framing video in c#

### ISSUE THREAD

**Issue by HadeelHassan** [accord-net/framework#772]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

If you would like to submit an issue, please include a sample of the code you are trying to execute, as well as any data you might be using in your experiment, such as data tables, images, anything that might be necessary to reproduce the problem.
  
Note: If you would like to support the development for this feature or resolution of this bug, consider adding a bounty to it later in https://www.bountysource.com/teams/accord-net/issues

**Comment by HadeelHassan** [comment]
Hi every one 
I am using Accord.Net to make face detection program by Viola-Jones , the program worked very well in static images and in web-camera , but i need to extract faces in saved video, when i used FFmpeg of aforge.Net but an error is appear 
{"Could not load file or assembly 'AForge.Video.FFMPEG.dll' or one of its dependencies. The specified module could not be found.":"AForge.Video.FFMPEG.dll"}
I dont knnow why this happen, i downloaded dll fie from GitHub site and added it to project reference .
the detailes of this error is 
   at Viola_and_Jones_Results_2.Form1.button3_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Viola_and_Jones_Results_2.Program.Main() in d:\Hadeel\00 thesis\Face recognition\C #\Backup\Viola and Jones Results 2 - Copy\Viola and Jones Results 2\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Please any one can help???

**Comment by cesarsouza** [comment]
Hi @HadeelHassan,

It is very weird that you are getting an error with **AForge**.Video.FFMPEG. This library (named AForge) has been superseeded by Accord since a long time. Which source code are you using as an example?

If you have any references to any libraries starting with "AForge." in their name, please remove them, and replace by the ones that start with "Accord.", such as Accord.Video.FFMPEG.

**Comment by HadeelHassan** [comment]
@cesarsouza 
thanks a lot for your reply 
I will try and let you know

**Comment by HadeelHassan** [comment]
@cesarsouza  i have this error now 
The type or namespace name 'FFMPEG' does not exist in the namespace 'Accord.Video' (are you missing an assembly reference?) i took this FFMPEG.dll file from Accord.Net 3.6

**Comment by cesarsouza** [comment]
Are you using NuGet? Have you tried installing Accord.Video.FFMPEG using NuGet? It should take care of solving the right dependencies for you (please be sure to make a backup of your project before you attempt it, though).

**Comment by HadeelHassan** [comment]
what should i write in NuGet console??

**Comment by cesarsouza** [comment]
You do not need to use the console. Instead, right-click the name of your project in the Solution Browser and select "Manage NuGet packages".

See https://github.com/accord-net/framework/wiki/Getting-started for an example.

Then click on "Browse" and search for Accord.Video.FFMPEG. If you are using VS2017 it should look something like this:
![image](https://user-images.githubusercontent.com/528455/29291507-2032a734-8144-11e7-9c8c-965db7423c1e.png)

If your application is set to "Any CPU" and you have a 64-bits processor and OS, you can install the x64 version.

**Comment by HadeelHassan** [comment]
@cesarsouza 
you are really help me a lot , it is working now.
all thanks to you and to accord.net
